export const AUTH_CLASSNAMES = {
  socialProviders: "tfm-social-providers",
  socialAccountList: "tfm-social-account-list",
  grid: "tfm-social-account-list--grid",
  socialProvidersStatus: "tfm-social-status",
  socialProvidersError: "tfm-social-status--error",
  socialIcon: "tfm-social-icon",
  formGroup: "tfm-field-group",
  label: "tfm-field-label",
  input: "tfm-field-input",
  inputInvalid: "tfm-field-input--invalid",
  feedback: "tfm-field-feedback",
  inputGroup: "tfm-password-group",
  passwordToggle: "tfm-password-toggle",
  settings: "tfm-form-settings",
  checkboxLabel: "tfm-checkbox-label",
  forgotPassword: "tfm-forgot-password",
  submitButton: "tfm-primary-action",
  actions: "tfm-form-actions",
  backLink: "tfm-back-link",
  terms: "tfm-terms",
  termsError: "tfm-terms-error",
  recaptcha: "tfm-recaptcha"
} as const;
