apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: guac-init
          emptyDir: {}
        - name: guac-init-script
          configMap:
            name: guac-init-script
            defaultMode: 0755
      initContainers:
        - name: guacdb-init
          image: guacamole/guacamole:1.5.5
          command: ["/bin/sh", "/init/init.sh"]
          volumeMounts:
            - name: guac-init
              mountPath: /init
            - name: guac-init-script
              mountPath: /init/init.sh
              subPath: init.sh
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: guacamole
            - name: POSTGRES_PASSWORD
              value: guacpass
            - name: POSTGRES_DB
              value: guacamole
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: guac-init
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "guacamole", "-d", "guacamole"]
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 20
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "guacamole", "-d", "guacamole"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: db
      port: 5432
      targetPort: 5432
